import express from 'express';
import crypto from 'node:crypto';
import { z } from 'zod';
import { pool, withTransaction, audit } from '../db.js';
import { config } from '../config.js';
import { requireAuth, requireAdmin, requirePlayOpen, csrf, rateLimit } from '../middleware/auth.js';
import { allGames, allGameMap } from '../catalog.js';
import { games } from '../games/index.js';
import { createChallenge, acceptChallenge, declineChallenge, listChallenges } from '../services/challenges.js';
import { getMatchForUser, listRecentMatches, checkMatchTimeout } from '../services/matches.js';
import { publicSiteConfig, getSetting, setSetting, getPlayStatus } from '../services/site.js';
import { getProfileProgress } from '../services/rewards.js';
import { startSoloRun, finishSoloRun } from '../services/solo.js';
import { listChat } from '../services/chat.js';
import { queueStatus, myQueueState, queueUsers } from '../services/matchmaking.js';

const router=express.Router();router.use(requireAuth);router.use(rateLimit({prefix:'api',limit:240,windowSeconds:60,keyFn:req=>req.session.userId}));
const uuid=z.string().uuid();
const challengeSchema=z.object({gameKey:z.string().max(40),targetUserId:uuid.nullish(),targetOfficeGroupId:uuid.nullish()}).strict().refine(v=>Boolean(v.targetUserId)!==Boolean(v.targetOfficeGroupId),{message:'Phải chọn đúng một đối thủ: user hoặc khối'});
const officeSchema=z.object({name:z.string().trim().min(1).max(80),code:z.string().trim().toUpperCase().regex(/^[A-Z0-9_-]{1,24}$/)}).strict();
const assignSchema=z.object({officeGroupId:uuid.nullable()}).strict();
const soloFinishSchema=z.object({runId:uuid,nonce:z.string().min(20).max(80),score:z.number().int().min(0).max(2_000_000_000),durationMs:z.number().int().min(0).max(3_600_000),meta:z.record(z.any()).optional()}).strict();
const imageAsset=z.string().max(700).refine(v=>!v.includes('..')&&(v===''||/^\/(assets|custom)\/[A-Za-z0-9_./-]+$/.test(v)||/^https:\/\/images\.unsplash\.com\//.test(v)),'Chỉ dùng /assets, /custom hoặc images.unsplash.com');
const localAsset=z.string().max(500).refine(v=>!v.includes('..')&&(v===''||/^\/(assets|custom)\/[A-Za-z0-9_./-]+$/.test(v)),'Âm thanh phải là file local /assets hoặc /custom');
const brandingSchema=z.object({siteName:z.string().trim().min(2).max(50),tagline:z.string().trim().max(150),heroImage:imageAsset,secondaryImage:imageAsset,backgroundImage:imageAsset,ambientSound:localAsset,gameSound:localAsset,musicVolume:z.number().int().min(5).max(100).optional(),sfxVolume:z.number().int().min(5).max(100).optional(),announcement:z.string().trim().max(240)}).strict();
const validTimeZone=v=>{try{new Intl.DateTimeFormat('en-US',{timeZone:v}).format();return true;}catch{return false;}};
const scheduleSchema=z.object({timezone:z.string().min(1).max(80).refine(validTimeZone,'Timezone không hợp lệ'),enabled:z.boolean(),windows:z.array(z.object({label:z.string().min(1).max(50),start:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),end:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),days:z.array(z.number().int().min(0).max(6)).min(1).max(7)}).strict()).min(1).max(6)}).strict();
const gameConfigSchema=z.object({enabled:z.boolean().optional(),leaderboardEnabled:z.boolean().optional(),xpMultiplier:z.number().min(0).max(10).optional(),pointMultiplier:z.number().min(0).max(10).optional(),aiDifficulty:z.enum(['hard','nightmare','impossible']).optional(),speedStart:z.number().min(.2).max(10).optional(),speedMax:z.number().min(.2).max(20).optional(),scoreCap:z.number().int().min(10).max(2_000_000_000).optional(),minRunSeconds:z.number().int().min(1).max(3600).optional()}).strict();
const userStatusSchema=z.object({status:z.enum(['active','suspended'])}).strict();
const adjustSchema=z.object({xpDelta:z.number().int().min(-10000).max(10000),pointsDelta:z.number().int().min(-10000).max(10000),reason:z.string().trim().min(5).max(200)}).strict();
const releaseSchema=z.object({version:z.string().trim().min(1).max(30),title:z.string().trim().min(2).max(120),body:z.string().trim().max(2000),items:z.array(z.string().trim().min(1).max(240)).max(20),releaseDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)}).strict();
const economySchema=z.object({soloDailyXpCap:z.number().int().min(0).max(100000),soloDailyPointCap:z.number().int().min(0).max(100000),pvpWinXp:z.number().int().min(0).max(10000),pvpLoseXp:z.number().int().min(0).max(10000),pvpDrawXp:z.number().int().min(0).max(10000),pvpWinPoints:z.number().int().min(0).max(10000),pvpLosePoints:z.number().int().min(0).max(10000),pvpDrawPoints:z.number().int().min(0).max(10000)}).strict();
const chatSettingsSchema=z.object({cooldownSeconds:z.number().int().min(1).max(120),maxLength:z.number().int().min(20).max(300)}).strict();
function parse(schema,value){const out=schema.safeParse(value);if(!out.success){const e=new Error('Dữ liệu gửi lên không hợp lệ');e.status=400;e.code='VALIDATION_ERROR';e.details=out.error.issues.map(i=>({path:i.path.join('.'),message:i.message}));throw e;}return out.data;}

router.get('/me',async(req,res)=>{const {rows}=await pool.query(`SELECT u.id,u.email,u.display_name,u.avatar_url,u.role,u.status,u.office_group_id,o.name office_name,o.code office_code FROM users u LEFT JOIN office_groups o ON o.id=u.office_group_id WHERE u.id=$1`,[req.session.userId]);if(!rows[0])return res.status(401).json({error:'AUTH_REQUIRED'});if(rows[0].status!=='active')return res.status(403).json({error:'ACCOUNT_SUSPENDED',message:'Tài khoản đã bị tạm khóa.'});const u=rows[0];res.json({user:{id:u.id,email:u.email,name:u.display_name,avatarUrl:u.avatar_url,role:u.role,officeGroup:u.office_group_id?{id:u.office_group_id,name:u.office_name,code:u.office_code}:null},progress:await getProfileProgress(u.id),csrfToken:req.session.csrfToken,hostedDomain:config.hostedDomain});});
router.get('/site',async(req,res)=>res.json(await publicSiteConfig()));
router.get('/games',async(req,res)=>{const {rows}=await pool.query('SELECT * FROM game_configs ORDER BY game_key');const cm=new Map(rows.map(r=>[r.game_key,r]));const isAdmin=req.session?.userId?(await pool.query("SELECT role FROM users WHERE id=$1",[req.session.userId])).rows[0]?.role==='admin':false;const all=allGames.map(g=>{const c=cm.get(g.key)||{};return {...g,online:true,pvp:g.pvp&&games.has(g.key),enabled:c.enabled==null?true:Boolean(Number(c.enabled)),leaderboardEnabled:c.leaderboard_enabled==null?true:Boolean(Number(c.leaderboard_enabled)),aiDifficulty:c.ai_difficulty||'nightmare',speedStart:Number(c.speed_start||1),speedMax:Number(c.speed_max||2.8)};});res.json({games:isAdmin?all:all.filter(g=>g.enabled)});});
router.get('/offices',async(req,res)=>{const {rows}=await pool.query('SELECT id,name,code FROM office_groups ORDER BY name');res.json({offices:rows});});
router.get('/play-status',async(req,res)=>res.json(await getPlayStatus()));
router.get('/releases',async(req,res)=>{const {rows}=await pool.query('SELECT id,version,title,body,items,release_date,created_at FROM releases ORDER BY release_date DESC,created_at DESC LIMIT 60');res.json({releases:rows});});
router.get('/chat',async(req,res)=>res.json({messages:await listChat(70)}));
router.get('/matchmaking/status',async(req,res)=>res.json({queues:await queueStatus()}));
router.get('/matchmaking/users',async(req,res)=>res.json({users:await queueUsers()}));
router.get('/matchmaking/me',async(req,res)=>res.json(await myQueueState(req.session.userId,typeof req.query.gameKey==='string'&&req.query.gameKey?req.query.gameKey:null)));

router.get('/lobby/users',async(req,res)=>{const AI_ID='00000000-0000-0000-0000-000000000000';const {rows}=await pool.query(`SELECT u.id,u.display_name,u.avatar_url,u.office_group_id,o.name office_name,u.xp,u.points FROM users u LEFT JOIN office_groups o ON o.id=u.office_group_id WHERE u.id<>$1 AND u.id<>$2 AND u.status='active' ORDER BY u.last_login_at DESC LIMIT 180`,[req.session.userId,AI_ID]);const presence=req.app.get('presence')||new Map();res.json({users:rows.map(r=>({id:r.id,name:r.display_name,avatarUrl:r.avatar_url,officeGroup:r.office_group_id?{id:r.office_group_id,name:r.office_name}:null,xp:Number(r.xp),points:Number(r.points),online:presence.has(r.id)}))});});

router.get('/challenges',async(req,res)=>res.json({challenges:await listChallenges(req.session.userId)}));
router.post('/challenges',csrf,requirePlayOpen,rateLimit({prefix:'challenge-create',limit:20,windowSeconds:60,keyFn:req=>req.session.userId}),async(req,res)=>{const body=parse(challengeSchema,req.body);if(!games.has(body.gameKey))return res.status(400).json({error:'UNSUPPORTED_GAME'});const c=await createChallenge({creatorId:req.session.userId,...body});const io=req.app.get('io');if(c.target_user_id)io?.to(`user:${c.target_user_id}`).emit('challenge:new',{id:c.id});if(c.target_office_group_id)io?.to(`office:${c.target_office_group_id}`).emit('challenge:new',{id:c.id});res.status(201).json({challenge:{id:c.id}});});
router.post('/challenges/:id/accept',csrf,requirePlayOpen,async(req,res)=>{const id=parse(uuid,req.params.id),result=await acceptChallenge(id,req.session.userId);const io=req.app.get('io');io?.to(`user:${result.creatorId}`).emit('match:created',{matchId:result.matchId});io?.to(`user:${req.session.userId}`).emit('match:created',{matchId:result.matchId});res.json({matchId:result.matchId});});
router.post('/challenges/:id/decline',csrf,async(req,res)=>{const id=parse(uuid,req.params.id),r=await declineChallenge(id,req.session.userId);req.app.get('io')?.to(`user:${r.creator_id}`).emit('challenge:changed',{id});res.status(204).end();});
router.get('/matches',async(req,res)=>res.json({matches:await listRecentMatches(req.session.userId)}));
router.get('/matches/:id',async(req,res)=>{const id=parse(uuid,req.params.id);await checkMatchTimeout(id).catch(()=>{});res.json({match:await getMatchForUser(id,req.session.userId)});});

router.post('/solo/:gameKey/start',csrf,requirePlayOpen,rateLimit({prefix:'solo-start',limit:80,windowSeconds:60,keyFn:req=>req.session.userId}),async(req,res)=>res.status(201).json(await startSoloRun(req.session.userId,String(req.params.gameKey))));
router.post('/solo/:gameKey/finish',csrf,requirePlayOpen,rateLimit({prefix:'solo-finish',limit:80,windowSeconds:60,keyFn:req=>req.session.userId}),async(req,res)=>{const body=parse(soloFinishSchema,req.body);try{const result=await finishSoloRun(req.session.userId,body,String(req.params.gameKey));req.app.get('io')?.to(`user:${req.session.userId}`).emit('progress:update',{progress:await getProfileProgress(req.session.userId),achievements:result.reward.achievements});res.json(result);}catch(error){await audit(req.session.userId,'solo.reject',body.runId,{gameKey:String(req.params.gameKey).slice(0,40),code:error.code||'REJECTED',score:body.score,durationMs:body.durationMs}).catch(()=>{});throw error;}});

router.get('/leaderboards/users',async(req,res)=>{const gameKey=String(req.query.gameKey||'').slice(0,40);if(!allGameMap.has(gameKey))return res.status(400).json({error:'BAD_GAME'});const cfg=(await pool.query('SELECT enabled,leaderboard_enabled FROM game_configs WHERE game_key=$1',[gameKey])).rows[0];if(!cfg?.enabled)return res.status(404).json({error:'GAME_DISABLED',message:'Game đang được admin ẩn.'});if(!cfg?.leaderboard_enabled)return res.status(404).json({error:'LEADERBOARD_DISABLED',message:'BXH của game đang tắt.'});const AI_ID='00000000-0000-0000-0000-000000000000';if(games.has(gameKey)){const {rows}=await pool.query(`SELECT u.id,u.display_name name,u.avatar_url,o.name office_name,r.rating,r.played,r.wins,r.losses,r.draws FROM ratings r JOIN users u ON u.id=r.user_id LEFT JOIN office_groups o ON o.id=u.office_group_id WHERE r.game_key=$1 AND u.id<>$2 ORDER BY r.rating DESC,r.played DESC LIMIT 100`,[gameKey,AI_ID]);return res.json({type:'rating',leaderboard:rows});}const {rows}=await pool.query(`SELECT u.id,u.display_name name,u.avatar_url,o.name office_name,s.best_score,s.plays,s.last_score,s.updated_at FROM game_scores s JOIN users u ON u.id=s.user_id LEFT JOIN office_groups o ON o.id=u.office_group_id WHERE s.game_key=$1 AND u.id<>$2 ORDER BY s.best_score DESC,s.updated_at ASC LIMIT 100`,[gameKey,AI_ID]);res.json({type:'score',leaderboard:rows});});
router.get('/leaderboards/progression',async(req,res)=>{const AI_ID='00000000-0000-0000-0000-000000000000';const {rows}=await pool.query(`SELECT u.id,u.display_name name,u.avatar_url,o.name office_name,u.xp,u.points,u.total_games FROM users u LEFT JOIN office_groups o ON o.id=u.office_group_id WHERE u.status='active' AND u.id<>$1 ORDER BY u.xp DESC,u.points DESC LIMIT 100`,[AI_ID]);res.json({leaderboard:rows});});
router.get('/leaderboards/offices',async(req,res)=>{const {rows}=await pool.query(`WITH participant_results AS (SELECT m.id,m.player1_id user_id,u1.office_group_id,CASE WHEN m.winner_id IS NULL THEN 1 WHEN m.winner_id=m.player1_id THEN 3 ELSE 0 END points,CASE WHEN m.winner_id=m.player1_id THEN 1 ELSE 0 END wins FROM matches m JOIN users u1 ON u1.id=m.player1_id JOIN users u2 ON u2.id=m.player2_id WHERE m.status='finished' AND u1.office_group_id IS NOT NULL AND u2.office_group_id IS NOT NULL AND u1.office_group_id<>u2.office_group_id UNION ALL SELECT m.id,m.player2_id,u2.office_group_id,CASE WHEN m.winner_id IS NULL THEN 1 WHEN m.winner_id=m.player2_id THEN 3 ELSE 0 END,CASE WHEN m.winner_id=m.player2_id THEN 1 ELSE 0 END FROM matches m JOIN users u1 ON u1.id=m.player1_id JOIN users u2 ON u2.id=m.player2_id WHERE m.status='finished' AND u1.office_group_id IS NOT NULL AND u2.office_group_id IS NOT NULL AND u1.office_group_id<>u2.office_group_id) SELECT o.id,o.name,o.code,CAST(COALESCE(SUM(p.points),0) AS SIGNED) points,CAST(COUNT(p.id) AS SIGNED) matches,CAST(COALESCE(SUM(p.wins),0) AS SIGNED) wins FROM office_groups o LEFT JOIN participant_results p ON p.office_group_id=o.id GROUP BY o.id,o.name,o.code ORDER BY points DESC,wins DESC,o.name`);res.json({leaderboard:rows});});

router.get('/admin/overview',requireAdmin,async(req,res)=>{const [[users],[matches],[chat],[runs]]=await Promise.all([pool.query("SELECT COUNT(*) n FROM users WHERE status='active'"),pool.query("SELECT COUNT(*) n FROM matches WHERE created_at>UTC_TIMESTAMP()-INTERVAL 24 HOUR"),pool.query("SELECT COUNT(*) n FROM chat_messages WHERE created_at>UTC_TIMESTAMP()-INTERVAL 24 HOUR AND deleted_at IS NULL"),pool.query("SELECT COUNT(*) n FROM solo_runs WHERE started_at>UTC_TIMESTAMP()-INTERVAL 24 HOUR")].map(p=>p.then(x=>x.rows)));res.json({stats:{users:users.n,matches24h:matches.n,chat24h:chat.n,runs24h:runs.n},playStatus:await getPlayStatus()});});
router.get('/admin/users',requireAdmin,async(req,res)=>{const q=String(req.query.q||'').slice(0,80);const {rows}=await pool.query(`SELECT u.id,u.email,u.display_name,u.avatar_url,u.role,u.status,u.office_group_id,o.name office_name,u.xp,u.points,u.total_games,u.last_login_at FROM users u LEFT JOIN office_groups o ON o.id=u.office_group_id WHERE $1='' OR LOWER(u.email) LIKE CONCAT('%',LOWER($1),'%') OR LOWER(u.display_name) LIKE CONCAT('%',LOWER($1),'%') ORDER BY u.last_login_at DESC LIMIT 250`,[q]);res.json({users:rows});});
router.post('/admin/offices',requireAdmin,csrf,async(req,res)=>{const b=parse(officeSchema,req.body),id=crypto.randomUUID();await pool.query('INSERT INTO office_groups(id,name,code) VALUES($1,$2,$3)',[id,b.name,b.code]);const office=(await pool.query('SELECT id,name,code FROM office_groups WHERE id=$1',[id])).rows[0];await audit(req.session.userId,'admin.office.create',id,{code:b.code});res.status(201).json({office});});
router.patch('/admin/users/:id/office',requireAdmin,csrf,async(req,res)=>{const id=parse(uuid,req.params.id),b=parse(assignSchema,req.body);if(b.officeGroupId&&!((await pool.query('SELECT 1 FROM office_groups WHERE id=$1',[b.officeGroupId])).rowCount))return res.status(404).json({error:'OFFICE_NOT_FOUND'});if(!((await pool.query('SELECT 1 FROM users WHERE id=$1',[id])).rowCount))return res.status(404).json({error:'USER_NOT_FOUND'});await pool.query('UPDATE users SET office_group_id=$2 WHERE id=$1',[id,b.officeGroupId]);await audit(req.session.userId,'admin.user.office_assign',id,{officeGroupId:b.officeGroupId});res.status(204).end();});
router.patch('/admin/users/:id/status',requireAdmin,csrf,async(req,res)=>{const id=parse(uuid,req.params.id),b=parse(userStatusSchema,req.body);if(id===req.session.userId&&b.status==='suspended')return res.status(400).json({error:'CANNOT_SUSPEND_SELF'});await pool.query('UPDATE users SET status=$2 WHERE id=$1',[id,b.status]);await audit(req.session.userId,'admin.user.status',id,b);if(b.status==='suspended')req.app.get('io')?.to(`user:${id}`).disconnectSockets(true);res.status(204).end();});
router.post('/admin/users/:id/adjust',requireAdmin,csrf,async(req,res)=>{const id=parse(uuid,req.params.id),b=parse(adjustSchema,req.body);const row=await withTransaction(async client=>{const current=(await client.query('SELECT id FROM users WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!current)return null;await client.query('UPDATE users SET xp=GREATEST(0,CAST(xp AS SIGNED)+$2),points=GREATEST(0,CAST(points AS SIGNED)+$3) WHERE id=$1',[id,b.xpDelta,b.pointsDelta]);return (await client.query('SELECT xp,points FROM users WHERE id=$1',[id])).rows[0];});if(!row)return res.status(404).json({error:'USER_NOT_FOUND'});await audit(req.session.userId,'admin.user.adjust',id,b);res.json({xp:Number(row.xp),points:Number(row.points)});});
router.get('/admin/settings',requireAdmin,async(req,res)=>{const {rows}=await pool.query('SELECT setting_key,value,updated_at FROM site_settings ORDER BY setting_key');res.json({settings:Object.fromEntries(rows.map(r=>[r.setting_key,r.value]))});});
router.put('/admin/settings/branding',requireAdmin,csrf,async(req,res)=>{const b=parse(brandingSchema,req.body);await setSetting('branding',b,req.session.userId);await audit(req.session.userId,'admin.settings.branding',null);req.app.get('io')?.emit('site:config',{branding:b});res.json({branding:b});});
router.put('/admin/settings/playSchedule',requireAdmin,csrf,async(req,res)=>{const b=parse(scheduleSchema,req.body);await setSetting('playSchedule',b,req.session.userId);await audit(req.session.userId,'admin.settings.schedule',null,b);req.app.get('io')?.emit('site:status',await getPlayStatus());res.json({playSchedule:b});});
router.put('/admin/settings/economy',requireAdmin,csrf,async(req,res)=>{const b=parse(economySchema,req.body);await setSetting('economy',b,req.session.userId);await audit(req.session.userId,'admin.settings.economy',null,b);res.json({economy:b});});
router.put('/admin/settings/chat',requireAdmin,csrf,async(req,res)=>{const b=parse(chatSettingsSchema,req.body);await setSetting('chat',b,req.session.userId);await audit(req.session.userId,'admin.settings.chat',null,b);req.app.get('io')?.emit('site:chat-config',{chat:b});res.json({chat:b});});
router.get('/admin/game-configs',requireAdmin,async(req,res)=>{const {rows}=await pool.query('SELECT * FROM game_configs ORDER BY game_key');res.json({configs:rows});});
router.patch('/admin/game-configs/:gameKey',requireAdmin,csrf,async(req,res)=>{const gameKey=String(req.params.gameKey);if(!allGameMap.has(gameKey))return res.status(404).json({error:'GAME_NOT_FOUND'});const b=parse(gameConfigSchema,req.body);const map={enabled:'enabled',leaderboardEnabled:'leaderboard_enabled',xpMultiplier:'xp_multiplier',pointMultiplier:'point_multiplier',aiDifficulty:'ai_difficulty',speedStart:'speed_start',speedMax:'speed_max',scoreCap:'score_cap',minRunSeconds:'min_run_seconds'};const entries=Object.entries(b);if(!entries.length)return res.status(204).end();const vals=[gameKey],sets=entries.map(([k,v],i)=>{vals.push(v);return `${map[k]}=$${i+2}`});await pool.query(`UPDATE game_configs SET ${sets.join(',')},updated_at=UTC_TIMESTAMP() WHERE game_key=$1`,vals);if(b.enabled===false){await Promise.all([pool.query('DELETE FROM match_queue WHERE game_key=$1',[gameKey]),pool.query("UPDATE challenges SET status='cancelled' WHERE game_key=$1 AND status='pending'",[gameKey])]);}await audit(req.session.userId,'admin.game.config',gameKey,b);if(Object.prototype.hasOwnProperty.call(b,'enabled')||Object.prototype.hasOwnProperty.call(b,'leaderboardEnabled'))req.app.get('io')?.emit('game:config',{gameKey,enabled:b.enabled,leaderboardEnabled:b.leaderboardEnabled});res.status(204).end();});
router.get('/admin/audit',requireAdmin,async(req,res)=>{const limit=Math.max(20,Math.min(200,Number(req.query.limit)||120));const {rows}=await pool.query(`SELECT a.id,a.event_type,a.target_id,a.metadata,a.created_at,u.display_name actor_name,u.email actor_email FROM audit_log a LEFT JOIN users u ON u.id=a.actor_id ORDER BY a.id DESC LIMIT $1`,[limit]);res.json({events:rows});});
router.delete('/admin/chat/:id',requireAdmin,csrf,async(req,res)=>{const id=z.coerce.number().int().positive().parse(req.params.id);const changed=await pool.query('UPDATE chat_messages SET deleted_at=UTC_TIMESTAMP(),deleted_by=$2 WHERE id=$1 AND deleted_at IS NULL',[id,req.session.userId]);if(!changed.rowCount)return res.status(404).json({error:'CHAT_NOT_FOUND'});await audit(req.session.userId,'admin.chat.delete',String(id));req.app.get('io')?.emit('chat:deleted',{id});res.status(204).end();});
router.post('/admin/releases',requireAdmin,csrf,async(req,res)=>{const b=parse(releaseSchema,req.body),id=crypto.randomUUID();await pool.query('INSERT INTO releases(id,version,title,body,items,release_date,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,b.version,b.title,b.body,JSON.stringify(b.items),b.releaseDate,req.session.userId]);const release=(await pool.query('SELECT * FROM releases WHERE id=$1',[id])).rows[0];await audit(req.session.userId,'admin.release.create',id,{version:b.version});req.app.get('io')?.emit('release:new',{release});res.status(201).json({release});});
router.patch('/admin/releases/:id',requireAdmin,csrf,async(req,res)=>{const id=parse(uuid,req.params.id),b=parse(releaseSchema,req.body);const changed=await pool.query('UPDATE releases SET version=$2,title=$3,body=$4,items=$5,release_date=$6 WHERE id=$1',[id,b.version,b.title,b.body,JSON.stringify(b.items),b.releaseDate]);if(!changed.rowCount)return res.status(404).json({error:'RELEASE_NOT_FOUND'});const release=(await pool.query('SELECT * FROM releases WHERE id=$1',[id])).rows[0];await audit(req.session.userId,'admin.release.update',id,{version:b.version});req.app.get('io')?.emit('release:changed',{id,release});res.json({release});});
router.delete('/admin/releases/:id',requireAdmin,csrf,async(req,res)=>{const id=parse(uuid,req.params.id);const changed=await pool.query('DELETE FROM releases WHERE id=$1',[id]);if(!changed.rowCount)return res.status(404).json({error:'RELEASE_NOT_FOUND'});await audit(req.session.userId,'admin.release.delete',id);req.app.get('io')?.emit('release:changed',{id,deleted:true});res.status(204).end();});

export default router;
