import http from 'node:http';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import express from 'express';
import session from 'express-session';
import helmet from 'helmet';
import { Server as SocketIOServer } from 'socket.io';
import { config } from './config.js';
import { initDb, pool } from './db.js';
import { createSessionStore } from './session-store.js';
import { startGoogle, googleCallback, logout } from './auth/google.js';
import { requireAuth, requirePlayOpen, csrf, rateLimit } from './middleware/auth.js';
import apiRouter from './routes/api.js';
import adminExtraRouter,{ensureAdminExtraMigrations} from './routes/admin-extra.js';
import testUsersRouter,{ensureTestUsers,handleTestLogin,installTestEventGuard} from './routes/test-users.js';
import { configureSockets } from './sockets.js';
import { ensureAiPlayer } from './services/ai.js';
import { ensureProgressionV2 } from './services/progression-v2.js';
const __dirname=path.dirname(fileURLToPath(import.meta.url)),publicDir=path.resolve(__dirname,'../public');
const app=express();app.disable('x-powered-by');if(config.trustProxy)app.set('trust proxy',config.trustProxy);
app.get('/healthz',(req,res)=>res.json({ok:true,service:'quan-giai-tri'}));
if(config.isProd)app.use((req,res,next)=>req.secure?next():res.redirect(308,`${config.appOrigin}${req.originalUrl}`));
const appUrl=new URL(config.appOrigin),wsOrigin=`${appUrl.protocol==='https:'?'wss:':'ws:'}//${appUrl.host}`;
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'data:','https://*.googleusercontent.com','https://images.unsplash.com'],mediaSrc:["'self'"],connectSrc:["'self'",wsOrigin],fontSrc:["'self'"],objectSrc:["'none'"],baseUri:["'self'"],frameAncestors:["'none'"],formAction:["'self'"]}},referrerPolicy:{policy:'no-referrer'},hsts:config.isProd?{maxAge:31536000,includeSubDomains:true,preload:false}:false,crossOriginEmbedderPolicy:false}));
app.use((req,res,next)=>{res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=(), payment=(), usb=()');next();});
app.use(['/auth','/api','/solo'],(req,res,next)=>{res.setHeader('Cache-Control','no-store');next();});
app.use(express.json({limit:config.maxBodyBytes,type:'application/json'}));
await initDb();
await ensureAdminExtraMigrations();
await ensureProgressionV2();
await ensureTestUsers();
await ensureAiPlayer();
const sessionMiddleware=session({name:config.isProd?'__Host-qgt.sid':'qgt.sid',secret:config.sessionSecret,store:createSessionStore(),resave:false,saveUninitialized:false,rolling:true,proxy:config.isProd?true:undefined,cookie:{httpOnly:true,secure:config.isProd,sameSite:'lax',path:'/',maxAge:config.sessionMaxAgeMs}});app.use(sessionMiddleware);
app.get('/auth/google',rateLimit({prefix:'auth-start',limit:20,windowSeconds:600}),startGoogle);app.get('/auth/google/callback',rateLimit({prefix:'auth-callback',limit:30,windowSeconds:600}),googleCallback);app.get('/auth/test-login',rateLimit({prefix:'auth-test-login',limit:30,windowSeconds:600}),handleTestLogin);app.post('/auth/logout',requireAuth,csrf,logout);
app.use('/api',testUsersRouter);
app.use('/api',apiRouter);
app.use('/api',adminExtraRouter);
app.use('/solo',requireAuth,requirePlayOpen,express.static(path.join(publicDir,'solo'),{index:'index.html',maxAge:0}));
app.use('/custom',requireAuth,express.static(path.join(publicDir,'custom'),{index:false,maxAge:config.isProd?'1h':0,dotfiles:'deny'}));
app.use(express.static(publicDir,{index:false,maxAge:config.isProd?'1h':0,dotfiles:'deny'}));
app.use((req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'NOT_FOUND'});if(req.method==='GET')return res.sendFile(path.join(publicDir,'index.html'));res.status(404).json({error:'NOT_FOUND'});});
const server=http.createServer(app),presence=new Map();app.set('presence',presence);
function socketRequestAllowed(req){
  const origin=req.headers.origin;
  if(origin)return origin===config.appOrigin;
  const host=String(req.headers.host||'').trim().toLowerCase();
  return host===appUrl.host.toLowerCase();
}
const io=new SocketIOServer(server,{serveClient:true,maxHttpBufferSize:config.maxSocketPayloadBytes,perMessageDeflate:false,cors:{origin:config.appOrigin,credentials:true,methods:['GET','POST']},allowRequest:(req,callback)=>callback(null,socketRequestAllowed(req))});io.engine.use(sessionMiddleware);app.set('io',io);installTestEventGuard(io);configureSockets(io,presence);
app.use((error,req,res,next)=>{void next;const status=Number(error.status)||500,requestId=req.get('x-request-id')||crypto.randomUUID();console.error(JSON.stringify({level:'error',event:'request_error',requestId,status,path:req.path,method:req.method,code:error.code||null,message:error.message}));if(res.headersSent)return;res.status(status).json({error:status<500?(error.code||'REQUEST_FAILED'):'INTERNAL_ERROR',message:status<500?error.message:'Có lỗi máy chủ.',requestId,...(error.details?{details:error.details}:{})});});
server.listen(config.port,()=>console.log(JSON.stringify({level:'info',event:'server_started',port:config.port,origin:config.appOrigin,hostedDomain:config.hostedDomain})));
async function shutdown(signal){console.log(JSON.stringify({level:'info',event:'shutdown',signal}));io.close();server.close();await pool.end();process.exit(0);}process.on('SIGTERM',()=>shutdown('SIGTERM'));process.on('SIGINT',()=>shutdown('SIGINT'));
