import { pool, withTransaction, audit } from '../db.js';
import { getSetting } from './site.js';
function err(status,message,code){const e=new Error(message);e.status=status;e.code=code;return e;}
export async function listChat(limit=60){const {rows}=await pool.query(`SELECT c.id,c.message,c.created_at,u.id user_id,u.display_name,u.avatar_url,o.name office_name FROM chat_messages c JOIN users u ON u.id=c.user_id LEFT JOIN office_groups o ON o.id=u.office_group_id WHERE c.deleted_at IS NULL AND u.is_test=0 ORDER BY c.id DESC LIMIT $1`,[Math.min(100,limit)]);return rows.reverse().map(r=>({id:r.id,message:r.message,createdAt:r.created_at,user:{id:r.user_id,name:r.display_name,avatarUrl:r.avatar_url,officeName:r.office_name}}));}
export async function sendChat(userId,message){
  message=String(message||'').trim().replace(/\s+/g,' ');const settings=await getSetting('chat')||{},max=Math.min(300,Number(settings.maxLength)||300),cooldown=Math.max(1,Number(settings.cooldownSeconds)||5);if(!message||message.length>max)throw err(400,`Tin nhắn phải từ 1-${max} ký tự`,'BAD_CHAT');
  const row=await withTransaction(async client=>{const u=(await client.query('SELECT status,last_chat_at,is_test FROM users WHERE id=$1 FOR UPDATE',[userId])).rows[0];if(!u||u.status!=='active')throw err(403,'Tài khoản không hoạt động','ACCOUNT_SUSPENDED');if(Number(u.is_test)===1)throw err(403,'Test account không phát chat công khai để tránh lộ user test.','TEST_CHAT_DISABLED');if(u.last_chat_at&&Date.now()-new Date(u.last_chat_at).getTime()<cooldown*1000)throw err(429,`Chờ ${cooldown}s giữa hai tin nhắn`,'CHAT_COOLDOWN');await client.query('UPDATE users SET last_chat_at=UTC_TIMESTAMP() WHERE id=$1',[userId]);const ins=await client.query('INSERT INTO chat_messages(user_id,message) VALUES($1,$2)',[userId,message]);return (await client.query('SELECT id,message,created_at FROM chat_messages WHERE id=$1',[ins.insertId])).rows[0];});
  await audit(userId,'chat.send',String(row.id));return row;
}
