import { pool } from '../db.js';
import { config } from '../config.js';
const cache=new Map();
export async function getSetting(key){const hit=cache.get(key);if(hit&&hit.until>Date.now())return hit.value;const {rows}=await pool.query('SELECT value FROM site_settings WHERE setting_key=$1',[key]);const value=rows[0]?.value??null;cache.set(key,{value,until:Date.now()+5000});return value;}
export async function setSetting(key,value,adminId){await pool.query(`INSERT INTO site_settings(setting_key,value,updated_by,updated_at) VALUES($1,$2,$3,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE value=VALUES(value),updated_by=VALUES(updated_by),updated_at=UTC_TIMESTAMP()`,[key,JSON.stringify(value),adminId]);cache.delete(key);}
function zonedParts(now=new Date(),timeZone=config.timezone){const parts=new Intl.DateTimeFormat('en-US',{timeZone,weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now);const map=Object.fromEntries(parts.map(p=>[p.type,p.value]));const days={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};return {day:days[map.weekday],minutes:Number(map.hour)*60+Number(map.minute)};}
const hm=s=>{const [h,m]=String(s).split(':').map(Number);return h*60+m;};
export async function getPlayStatus(now=new Date()){const schedule=await getSetting('playSchedule')||{enabled:false,timezone:config.timezone,windows:[]};if(schedule.enabled===false)return {open:true,message:'Mở toàn thời gian',schedule};const {day,minutes}=zonedParts(now,schedule.timezone||config.timezone);let active=null;for(const w of schedule.windows||[]){const start=hm(w.start),end=hm(w.end),days=w.days||[0,1,2,3,4,5,6];if(start<=end){if(days.includes(day)&&minutes>=start&&minutes<end){active=w;break;}}else{const prev=(day+6)%7;if((days.includes(day)&&minutes>=start)||(days.includes(prev)&&minutes<end)){active=w;break;}}}return {open:Boolean(active),message:active?`Đang trong khung ${active.label||`${active.start}-${active.end}`}`:'Quán đang đóng trong giờ làm việc. Hẹn gặp lại vào giờ giải trí.',window:active,schedule};}
export async function publicSiteConfig(){const [branding,playSchedule,economy,chat,security]=await Promise.all(['branding','playSchedule','economy','chat','security'].map(getSetting));return {branding,playSchedule,economy,chat,security,playStatus:await getPlayStatus()};}
